initial port to python 3
zopefoundation/Products.SQLAlchemyDA pull request #8
Opened 2020-11-09 18:35 UTC by jordic

2020-11-09 18:35 UTC, jordic commented
Moved from https://github.com/zopefoundation/Products.SQLAlchemyDA/pull/7

2020-11-09 19:20 UTC, dataflake commented
Thank you for creating the branch, I'll take a look tomorrow.

2020-11-09 19:39 UTC, jordic commented
Ideally we need to finish, merge and release z3c.sqlalchemy to be able to finish this port

2020-11-10 06:57 UTC, jugmac00 commented on Products/SQLAlchemyDA/da.py
>                  if k.startswith('_'):
what about..
`for k in list(d.keys())`

That way you do not need to copy the complete dictionary.

2020-11-10 07:08 UTC, icemac requested changes
This repository still needs a `.travis.yml` file, so the tests are run.
I think it should be added in a separate PR so this one does not get messed up with these changes.

2020-11-10 08:40 UTC, jordic commented
uploaded travis, but the package depends on z3c.sqlalchemy (new version), can I pin up (like in pip) a commit on the setup.py?
There's also a failure (when running with correct version on z3c.sqlalcemy. 
https://github.com/zopefoundation/Products.SQLAlchemyDA/blob/master/tests/test_SQLAlchemyDA.py#L162

Perhaps related to, this: 
https://github.com/zopefoundation/z3c.sqlalchemy/commit/796aea500a5770f019d69f391b503cf41a1f718f
cc: @mgedmin @dataflake

2020-11-10 08:41 UTC, dataflake requested changes

2020-11-10 08:41 UTC, dataflake commented on .travis.yml
> +    - 3.8
No. Please look at other Travis configs like https://github.com/zopefoundation/Zope/blob/4.x/.travis.yml and do it that way (except the email notification)

2020-11-10 08:41 UTC, dataflake commented on Products/SQLAlchemyDA/__init__.py
> +    from Products.SQLAlchemyDA.da import (SAWrapper, manage_addSAWrapper,
Make this a relative import again

2020-11-10 08:41 UTC, dataflake commented on Products/SQLAlchemyDA/da.py
> +        #    return unicode(s, self.encoding, 'ignore')
Don't just comment this out. Look at the intent and go from there. The intent is to safely convert bytes values into unencoded string values (unicode in Python 2, native string in Python 3).

2020-11-10 08:41 UTC, dataflake commented on tox.ini
> +    py36,
add py35, Zope 4 still supports it

2020-11-10 08:43 UTC, dataflake commented
> uploaded travis, but the package depends on z3c.sqlalchemy (new version), can I pin up (like in pip) a commit on the setup.py?
> There's also a failure (when running with correct version on z3c.sqlalcemy.

Ignore all test failures here until the dependencies have been released.

2020-11-10 08:44 UTC, jordic commented
When testing it localy, with an instance of zope5, I have that printed on the console
```2020-11-10 09:42:03 WARNING [SQLAlchemyDA:266][waitress-3] Unexpected failure to create SAWrapper: SAWrapper '1604183616.0983956.0.9049506331999768' already registered.
You can not register a wrapper twice under the same name.```

2020-11-10 13:31 UTC, dataflake commented
All housekeeping stuff is now done here. The status is one failing test. That probably requires someone with actual SQLAlchemy knowledge, so it's not me.

2020-11-10 13:41 UTC, jordic commented
Ohhh, so many thanks for the work, and the help on it!
Will try to dig on it, it's the same test that failed for me, I'm not sure, but it could be something related on the way we swapped transactions on z3c.sqlalchemy (the failing one ensures that after and insert, the session is commited). Perhaps it misses the registration? @mgedmin any ideas?

2020-11-10 14:03 UTC, mgedmin commented
I've never used sqlalchemy in any of my Zope-related stuff, so I don't know what to tell you.

The error message hints that the z3c.sqlalchemy fix (dropping the ZopeTransactionExtension) wasn't actually correct.  It looks like it tries to call register() multiple times for the same thing.

2020-11-10 18:27 UTC, jordic commented
Found a solution for the failure, but the problem seems to be related around the event system of sqlalchemy session.
 There are two parts, first of all:
1. session_maker it's a factory for creating sessions (the past commit on z3c.sqlalchemy) is wrong, we register the factory, not the session itself.

The second part that I'm still tring to figure why is that it needs to be registered as 'changed', if not, the session is never commited (just flushed), and that's why the test fails.

2020-11-11 04:40 UTC, jordic commented
> The first part is that session_maker it's a factory for creating sessions (the past commit on z3c.sqlalchemy) is wrong, we register the factory, not the session itself.
> 
> https://github.com/zopefoundation/z3c.sqlalchemy/compare/fix-register-session-events

There's no need for this. The sessionmaker is also a valid param to the event system. (z3c.sqlalchemy) it's fine how it's at master.

2020-11-11 07:07 UTC, icemac commented
I do not feel competent to review this PR.

2020-11-12 19:11 UTC, jordic commented
@dataflake I'm currently using this package on prod for python2.7 and planning to use it with python3. Do you agree to merge this branch and release a new version.
I can keep maintaining it.

2020-11-13 10:24 UTC, dataflake commented
This package **cannot** be released until `z3c.sqlalchemy` has been released.

2020-11-13 10:24 UTC, dataflake approved these changes

2020-11-13 13:10 UTC, merged

2020-11-13 13:50 UTC, jordic commented
So many thanks for the help with this port :)

2020-11-13 14:15 UTC, jugmac00 commented
Thanks for contributing, @jordic!

2020-11-13 14:17 UTC, dataflake commented
Products.SQLAlchemyDA 1.0 is now on PyPI.